Repository AlaskaAirlines/auro-button, pull requests merged in 2021-05, with the labels that each got.

#115 button: add support to display version in element
  .github/workflows/testPublish.yml
  package.json
  scripts/postCss.js
  scripts/prepForBuild.js
  scripts/removeNonRemPlugin.js
  scripts/staticStyles-template.js
  scripts/version.js
  src/auro-button.js
  src/version.js
Labels: Status: Complete and Ready to Merge, Status: Review Needed, Type: Feature

#118 fix: prevent errors with createElement
  src/auro-button.js
Labels: Status: Complete and Ready to Merge, Status: Review Needed, Type: Bug

#122 fix: default boolean props to false #121
  docs/api.md
  src/auro-button.js
Labels: Status: Review Needed
